import React, { useState } from 'react';
import { ShieldAlert, Users, Building2, Calendar, CheckCircle2, BriefcaseBusiness, LayoutDashboard, Search, XCircle } from 'lucide-react';
import { Complaint, UserProfile, Booking, Hall, ServiceProvider, BookingStatus } from '../types';
interface Props { currentUser:UserProfile; complaints:Complaint[]; bookings:Booking[]; halls:Hall[]; providers:ServiceProvider[]; onUpdateComplaintStatus:(id:string,status:Complaint['status'],reply?:string)=>void; onUpdateBookingStatus:(id:string,status:BookingStatus)=>Promise<void>|void; }
export const AdminHomeView:React.FC<Props>=({currentUser,complaints,bookings,halls,providers,onUpdateComplaintStatus,onUpdateBookingStatus})=>{
 const [tab,setTab]=useState<'dashboard'|'bookings'|'complaints'|'halls'|'providers'>('dashboard'); const [search,setSearch]=useState(''); const q=search.trim().toLowerCase();
 const pendingComplaints=complaints.filter(c=>c.status!=='تمت المعالجة'); const pendingBookings=bookings.filter(b=>b.status==='قيد المراجعة'||b.status==='pending');
 const nav=[['dashboard','الرئيسية',LayoutDashboard],['bookings','الحجوزات',Calendar],['complaints','الشكاوى',ShieldAlert],['halls','القاعات',Building2],['providers','مزودو الخدمة',BriefcaseBusiness]] as const;
 return <div className="max-w-7xl mx-auto px-4 py-6 space-y-5" dir="rtl" id="admin-home-dashboard">
 <header className="bg-gradient-to-r from-emerald-950 via-gray-900 to-amber-950 p-6 rounded-3xl text-white shadow-xl"><span className="bg-amber-400 text-black text-xs font-black px-3 py-1 rounded-full">لوحة المدير الكاملة</span><h1 className="text-2xl font-black mt-3">مرحباً، {currentUser.name}</h1><p className="text-xs text-gray-300 mt-1">إدارة الحجوزات والقاعات ومزودي الخدمة والشكاوى من مكان واحد</p></header>
 <nav className="flex gap-2 overflow-x-auto bg-white p-2 rounded-2xl border">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`px-4 py-2.5 rounded-xl text-xs font-bold flex items-center gap-1.5 shrink-0 ${tab===id?'bg-emerald-800 text-white':'hover:bg-gray-100'}`}><Icon className="w-4 h-4"/>{label}</button>)}</nav>
 {tab!=='dashboard'&&<label className="bg-white border rounded-2xl px-4 py-3 flex items-center gap-2"><Search className="w-4 h-4 text-emerald-700"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث بالاسم أو الهاتف أو المحافظة..." className="flex-1 outline-none text-xs"/></label>}
 {tab==='dashboard'&&<div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[[pendingBookings.length,'حجوزات معلقة',Calendar],[pendingComplaints.length,'شكاوى معلقة',ShieldAlert],[bookings.length,'كل الحجوزات',CheckCircle2],[halls.length,'القاعات',Building2],[providers.length,'مزودو الخدمة',Users]].map(([n,l,I]:any)=><div key={l} className="bg-white border rounded-2xl p-4"><I className="w-5 h-5 text-emerald-700"/><b className="text-2xl block mt-2">{n}</b><span className="text-xs text-gray-500">{l}</span></div>)}</div>}
 {tab==='bookings'&&<section className="space-y-3">{bookings.filter(b=>!q||`${b.itemName} ${b.customerName} ${b.customerPhone}`.toLowerCase().includes(q)).map(b=><div key={b.id} className="bg-white border rounded-2xl p-4 flex flex-wrap justify-between gap-3"><div><b className="text-sm">{b.itemName}</b><p className="text-xs text-gray-500">{b.customerName} • {b.customerPhone} • {b.date} • {b.timeSlot}</p><span className="text-[11px] font-bold">{b.status}</span></div>{(b.status==='قيد المراجعة'||b.status==='pending')&&<div className="flex gap-2"><button onClick={()=>void onUpdateBookingStatus(b.id,'مقبول')} className="px-3 py-2 bg-emerald-100 text-emerald-800 rounded-xl text-xs font-bold"><CheckCircle2 className="inline w-4 h-4"/> قبول</button><button onClick={()=>void onUpdateBookingStatus(b.id,'مرفوض')} className="px-3 py-2 bg-rose-100 text-rose-800 rounded-xl text-xs font-bold"><XCircle className="inline w-4 h-4"/> رفض</button></div>}</div>)}</section>}
 {tab==='complaints'&&<section className="space-y-3">{complaints.filter(c=>!q||`${c.userName} ${c.userPhone} ${c.subject}`.toLowerCase().includes(q)).map(c=><div key={c.id} className="bg-white p-5 rounded-2xl border space-y-2"><div className="flex justify-between"><b className="text-sm">{c.subject}</b><span className="text-xs">{c.status}</span></div><p className="text-xs text-gray-600">{c.userName} ({c.userPhone}) — {c.description}</p>{c.adminReply?<p className="p-2 bg-emerald-50 text-xs">رد الإدارة: {c.adminReply}</p>:<div className="flex gap-2"><input id={`reply-${c.id}`} className="flex-1 border rounded-xl px-3 text-xs" placeholder="رد الإدارة"/><button onClick={()=>{const el=document.getElementById(`reply-${c.id}`) as HTMLInputElement;if(el?.value)onUpdateComplaintStatus(c.id,'تمت المعالجة',el.value)}} className="px-4 py-2 bg-emerald-800 text-white rounded-xl text-xs font-bold">إرسال الرد</button></div>}</div>)}</section>}
 {tab==='halls'&&<section className="grid md:grid-cols-2 lg:grid-cols-3 gap-3">{halls.filter(h=>!q||`${h.name} ${h.city} ${h.phone||''}`.toLowerCase().includes(q)).map(h=><div key={h.id} className="bg-white border rounded-2xl overflow-hidden"><img src={h.coverImage||h.images?.[0]} className="w-full h-32 object-cover"/><div className="p-3"><b>{h.name}</b><p className="text-xs text-gray-500">{h.city} • {h.phone||'بلا هاتف'}</p></div></div>)}</section>}
 {tab==='providers'&&<section className="grid md:grid-cols-2 lg:grid-cols-3 gap-3">{providers.filter(p=>!q||`${p.name} ${p.city} ${p.phone}`.toLowerCase().includes(q)).map(p=><div key={p.id} className="bg-white border rounded-2xl p-3 flex gap-3"><img src={p.avatar||p.coverImage} className="w-16 h-16 rounded-full object-cover"/><div><b>{p.name}</b><p className="text-xs text-gray-500">{p.serviceCategory} • {p.city}</p><p className="text-xs dir-ltr">{p.phone}</p></div></div>)}</section>}
 </div>;
};
