import React from 'react';
import { Ban, Building2, Calendar, MapPin, Phone, RotateCcw, Shield, User, X } from 'lucide-react';
import { Booking, UserProfile } from '../types';
export const UserProfileModal:React.FC<{user:UserProfile|null;bookings:Booking[];isAdmin?:boolean;onClose:()=>void;onBlock?:(u:UserProfile,blocked:boolean)=>void;onOpenBusiness?:(u:UserProfile)=>void}>=({user,bookings,isAdmin,onClose,onBlock,onOpenBusiness})=>{
 if(!user)return null; const own=bookings.filter(b=>b.requesterId===user.id||b.targetOwnerId===user.id);
 return <div className="fixed inset-0 z-[70] bg-black/65 flex items-center justify-center p-3" dir="rtl"><div className="bg-white rounded-3xl max-w-xl w-full max-h-[92vh] overflow-y-auto shadow-2xl">
 <div className="relative h-40 bg-gradient-to-r from-emerald-950 to-amber-900 rounded-t-3xl overflow-hidden">{user.coverImageUrl&&<img src={user.coverImageUrl} className="w-full h-full object-cover opacity-60"/>}<button onClick={onClose} className="absolute top-3 left-3 p-2 bg-black/40 text-white rounded-full"><X className="w-4 h-4"/></button></div>
 <div className="px-5 -mt-12 relative pb-5 space-y-4"><div className="flex items-end gap-3"><div className="w-24 h-24 rounded-full border-4 border-white bg-emerald-100 overflow-hidden flex items-center justify-center">{user.profileImageUrl?<img src={user.profileImageUrl} className="w-full h-full object-cover"/>:<User className="w-9 h-9 text-emerald-700"/>}</div><div className="pb-2"><h2 className="text-xl font-black">{user.name}</h2><span className="text-xs bg-amber-100 px-2 py-1 rounded-full font-bold">{user.accountType}</span></div></div>
 <div className="grid grid-cols-2 gap-2 text-xs"><div className="p-3 bg-gray-50 rounded-xl"><Phone className="inline w-4 h-4"/> {user.phone}</div><div className="p-3 bg-gray-50 rounded-xl"><MapPin className="inline w-4 h-4"/> {user.city}</div><div className="p-3 bg-gray-50 rounded-xl"><Calendar className="inline w-4 h-4"/> {user.createdAt?new Date(user.createdAt).toLocaleString('ar-IQ'):'غير معروف'}</div><div className="p-3 bg-gray-50 rounded-xl"><Building2 className="inline w-4 h-4"/> {own.length} حجز</div></div>
 {user.isBlocked&&<div className="p-3 bg-rose-50 border border-rose-200 rounded-xl text-xs text-rose-800"><Shield className="inline w-4 h-4"/> الحساب محظور: {user.blockReason}</div>}
 {(user.accountType==='صاحب قاعة'||user.accountType==='مزود خدمة')&&<button onClick={()=>onOpenBusiness?.(user)} className="w-full py-3 bg-emerald-700 text-white rounded-xl text-xs font-bold">فتح الصفحة الرئيسية للحساب</button>}
 {isAdmin&&onBlock&&<button onClick={()=>{const action=user.isBlocked?'رفع الحظر عن':'حظر';if(confirm(`هل تؤكد ${action} ${user.name}؟`))onBlock(user,!user.isBlocked)}} className={`w-full py-3 rounded-xl text-xs font-bold flex justify-center gap-2 ${user.isBlocked?'bg-emerald-100 text-emerald-800':'bg-rose-600 text-white'}`}>{user.isBlocked?<RotateCcw className="w-4 h-4"/>:<Ban className="w-4 h-4"/>}{user.isBlocked?'رفع الحظر':'حظر المستخدم تماماً'}</button>}
 </div></div></div>;
};
